name: eazy-bank-microservices
services:

  configserver:
    image: winstyngyen/configserver:s8
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/Proautotype/eazybank-microservice-config.git"

  eurekaserver:
    image: winstyngyen/eurekaserver:s8
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"

  accounts:
    image: winstyngyen/accounts:s8
    container_name: accounts-ms
    ports:
      - "8080:8080"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      BUILD_VERSION: 1

  loans:
    image: winstyngyen/loans:s8
    container_name: loans-ms
    ports:
      - "8090:8090"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_APPLICATION_NAME: "loans"
      BUILD_VERSION: 1

  cards:
    image: winstyngyen/cards:s8
    container_name: cards-ms
    ports:
      - "9000:9000"
    extends:
      file: common-config.yml
      service: microservice-eureka-config
    environment:
      SPRING_APPLICATION_NAME: "cards"
      BUILD_VERSION: 1

networks:
  eazybank:
    driver: "bridge"

#command: ["sh", "-c", "printenv && java -jar /app.jar"]