server:
  port: 8090

spring:
  application:
    name: "loans"
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"

  datasource:
    url: jdbc:mysql://localhost:3307/loansDb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#logging:
#  level:
#    root: error
#    com.eazybytes: TRACE
