server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git
  #    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wellwinn/sacred-microservice-config.git
          clone-on-start: true
          default-label: main
          #clears cached resources in the server
          force-pull: true
          timeout: 10 #wait for 5 seconds else throw catch

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    cloud:
      bus:
        enabled: true
        refresh:
          enabled: true

encrypt:
  key: "WqZSulKIcs5NRJFfd59VSr4iuNZCYXuTFZk0Lw4SjAWsqyIuF2qfumaytYW6tIly"

management:
  endpoints:
    web:
      exposure:
        include: "*"